pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/ArtakOvakimyan/MO_team3', branch: 'main'
            }
        }
        stage('Setup Environment') {
            steps {
                sh '''#!/bin/bash
                python3 -m venv lab2_env
                source lab2_env/bin/activate
                pip install -r requirements.txt
                '''
            }
        }
        stage('Get Data') {
            steps {
                sh '''#!/bin/bash
                source lab2_env/bin/activate && python get_data.py
                '''
            }
        }
        stage('Preprocess Data') {
            steps {
                sh '''#!/bin/bash
                source lab2_env/bin/activate && python preprocess_data.py
                '''
            }
        }
        stage('Train Model') {
            steps {
                sh '''#!/bin/bash
                source lab2_env/bin/activate && python train_model.py
                '''
            }
        }
        stage('Evaluate Model') {
            steps {
                sh '''#!/bin/bash
                source lab2_env/bin/activate && python evaluate_model.py
                '''
            }
        }
    }
    post {
        always {
            echo 'Pipeline finished'
        }
        failure {
            echo 'Pipeline failed'
        }
    }
}
