services:
  app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./app:/app  # Для разработки с hot-reload
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0